## Scikit_learn:
In this we will se how to implement all the previous three libraries mentioned,Also will deal with another important module
i.e: Scikit-Learn



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## We need to find what how much patient are getting heart disease 

In [2]:
# importing heart disease file using pd
heart_disease=pd.read_csv("heart-disease (1).csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# Checking if our data has missing values or not 
heart_disease.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
# trying to split our data to make some prediction
X=heart_disease.drop(["target"],axis=1)
y=heart_disease["target"]

In [5]:
# checking X and y
X.head(5),y.head(5)

(   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
 0   63    1   3       145   233    1        0      150      0      2.3      0   
 1   37    1   2       130   250    0        1      187      0      3.5      0   
 2   41    0   1       130   204    0        0      172      0      1.4      2   
 3   56    1   1       120   236    0        1      178      0      0.8      2   
 4   57    0   0       120   354    0        1      163      1      0.6      2   
 
    ca  thal  
 0   0     1  
 1   0     2  
 2   0     2  
 3   0     2  
 4   0     2  ,
 0    1
 1    1
 2    1
 3    1
 4    1
 Name: target, dtype: int64)

In [6]:
# now importing train_test_Split to split our data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [7]:
X_train.size,X_test.size

(3146, 793)

In [8]:
# Now importibng our model RandomForestClassifier()
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
# now fit our training data to the model
clf.fit(X_train,y_train)

RandomForestClassifier()

In [9]:
# now lets check how much did it score on our training data
clf.score(X_train,y_train)

1.0

In [10]:
# checking on test data
clf.score(X_test,y_test)

0.8852459016393442

In [11]:
# prediction on our test data
y_preds=clf.predict(X_test)
y_preds

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1])

In [12]:
## importing some more evaluating metrics
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84        22
           1       0.92      0.90      0.91        39

    accuracy                           0.89        61
   macro avg       0.87      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61



In [13]:
confusion_matrix(y_test,y_preds)

array([[19,  3],
       [ 4, 35]])

In [14]:
# looking for accuracy score
accuracy_score(y_test,y_preds)

0.8852459016393442

## Now lets move toward our the next step what if we got raw data not all the data is numeric form 
 how to deal with such kind of data we will see it now 
 

In [15]:
# lets import a car sales data
car_sales=pd.read_csv("car-sales-extended.csv")
car_sales.head(5)

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [16]:
len(car_sales)

1000

In [17]:
# let see all the data is numeric or not
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [18]:
# we got that our data has some non-numeric value let see for is there any missing values
car_sales.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

We know that now our data has some non-numeric values and there is no missing data so we will move ahead to do all the procedure keeping all this in mind

we have two option using :
1) scikit Learn
2) pandas

we well be processing with both 

In [19]:
X=car_sales.drop("Price",axis=1)
y=car_sales["Price"]

In [20]:
# uwe need to convert using scikit learn
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour"]
One_hot=OneHotEncoder()
transformer =ColumnTransformer([("One_hot",
                                 One_hot,
                                 categorical_features)],
                               remainder="passthrough")

transformed_X=transformer.fit_transform(X)
transformed_X
                                 


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        3.54310e+04, 4.00000e+00],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.92714e+05, 5.00000e+00],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        8.47140e+04, 4.00000e+00],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 4.00000e+00],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        2.15883e+05, 4.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 4.00000e+00]], shape=(1000, 11))

In [21]:
## now the same process will beging
# importing train_test_split to split our data aslo importing the model
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(transformed_X,y,test_size=0.2)

In [22]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [23]:
# impofrom rting model
from sklearn.ensemble import RandomForestRegressor

model=RandomForestRegressor()
# fit the training data into the model
model.fit(X_train,y_train)

RandomForestRegressor()

In [24]:
model.score(X_train,y_train)

0.8947800522902917

In [25]:
# lets predict the output using X_test
y_preds=model.predict(X_test)
y_preds

array([14703.19, 21047.03, 21045.77, 12705.04, 13021.08, 14266.94,
       24487.79, 10412.  ,  9166.18, 14404.82, 10068.83, 13524.8 ,
       21152.63, 23392.69, 13120.18, 23013.33, 11679.96,  8473.05,
       17614.33, 14284.1 , 15225.43, 10006.64, 17527.97,  6399.92,
       14415.29, 11868.36,  5674.26, 18036.25, 12497.6 , 15064.9 ,
       11369.24, 25728.41, 17610.43, 10933.08, 13528.96, 25970.02,
       17257.8 , 24587.68, 18086.08, 14617.49, 11729.96, 10441.35,
       17659.71,  8311.26, 13730.46, 40027.81,  6750.49,  6631.  ,
        8087.86, 22850.57,  9939.9 , 22048.33, 39662.9 ,  9639.69,
       18036.41, 17440.06, 21939.95, 28208.64, 10808.75, 27960.7 ,
       22875.91, 10374.47,  9816.45, 21393.4 , 15863.09, 33212.18,
       17780.87, 21062.74, 12172.04, 16654.63, 24068.92, 20337.8 ,
       10575.68, 13602.82, 13056.12, 19306.39, 24099.82, 11094.68,
        8812.96, 21197.34, 25676.43, 11151.3 , 41133.37, 11043.98,
       20481.71, 15179.8 , 12011.8 , 46068.44, 17678.83, 17526

## now converting all the non-numeric data to numeric using pandas


In [26]:
dummies=pd.get_dummies(car_sales[["Make","Colour","Doors"]])
dummies
                       

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4     False        True        False        False         False   
1        5      True       False        False        False         False   
2        4     False        True        False        False         False   
3        4     False       False        False         True         False   
4        3     False       False         True        False         False   
..     ...       ...         ...          ...          ...           ...   
995      4     False       False        False         True          True   
996      3     False       False         True        False         False   
997      4     False       False         True        False         False   
998      4     False        True        False        False         False   
999      4     False       False        False         True         False   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          False         False       False          True  
1           True         False       False         False  
2          False         False       False          True  
3          False         False       False          True  
4           True         False       False         False  
..           ...           ...         ...           ...  
995        False         False       False         False  
996        False         False       False          True  
997         True         False       False         False  
998        False         False       False          True  
999         True         False       False         False  

[1000 rows x 10 columns]

## What if we have missing data :
   We can fill it with two option :
   1) with pandas
   2) with scikit learn


In [27]:
import pandas as pd
import numpy as np
# lets import the missing data df
car_sales_missing=pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [28]:
len(car_sales_missing)

1000

In [29]:
# lets check if there are some missing data or not
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [30]:
# Create X,y
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

In [31]:
# lets check that our data is numeric or not
car_sales_missing.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [32]:
# lets make all the data into numeric
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                              remainder="passthrough")

transformed_X=transformer.fit_transform(X)
transformed_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4000 stored elements and shape (1000, 16)>

In [33]:
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [34]:
car_sales_missing["Doors"].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

## Fill missing data with pandas

In [35]:
# fill the missing data with pandas
car_sales_missing["Make"].fillna("missing",inplace=True)

# fill missing data of colour
car_sales_missing["Colour"].fillna("missing",inplace=True)

# fill missing data of doors
car_sales_missing["Doors"].fillna(4,inplace=True)

# fill missing data of Odometer
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(),inplace=True)

C:\Users\Saurabh Guru\AppData\Local\Temp\ipykernel_60940\1141997566.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing["Make"].fillna("missing",inplace=True)
C:\Users\Saurabh Guru\AppData\Local\Temp\ipykernel_60940\1141997566.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behav

In [36]:
# lets check the missing Data
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [37]:
# now lets remove missing value of Price 
car_sales_missing.dropna(inplace=True)

In [38]:
len(car_sales_missing)

950

In [39]:
car_sales_missing.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [40]:
# Create X and y

In [41]:
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]


In [42]:
# lets conert all our data into numeric
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transormer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")

transformed_X=transformer.fit_transform(car_sales_missing)
transformed_X
                              

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]], shape=(950, 16))

## Fill missing data and transforming categorical data into numeric using scikit learn
 Step to do:
 1) Split your data first into(train/test)
 2) fill/transform the test and training data separately

In [43]:
# import our missing car_sales data
car_sales_missing=pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [44]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [45]:
# Drop the rows with no labels
car_sales_missing.dropna(subset=["Price"],inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [46]:
# Split X,y
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

# from sklearn import train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [47]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [48]:
# fill misisng value with scikit learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# fill categorical value with the missing value
cat_imputer=SimpleImputer(strategy="constant",fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",fill_value=4)
num_imputer=SimpleImputer(strategy="mean")

# Define Columns
cat_features=["Make","Colour"]
door_features=["Doors"]
num_features=["Odometer (KM)"]

#Create an imputer(Something that fill missing values)
imputer=ColumnTransformer([("cat_imputer",cat_imputer,cat_features),
                           ("door_imputer",door_imputer,door_features),
                           ("num_imputer",num_imputer,num_features)])

# fill Train and test value separately

filled_X_train=imputer.fit_transform(X_train)
filled_X_test=imputer.fit_transform(X_test)

# Check filled X_train
filled_X_train

array([['Nissan', 'Blue', 4.0, 141962.0],
       ['Nissan', 'Black', 4.0, 240536.0],
       ['Toyota', 'White', 4.0, 193629.0],
       ...,
       ['Toyota', 'White', 4.0, 110362.0],
       ['Toyota', 'Blue', 4.0, 205592.0],
       ['Toyota', 'White', 4.0, 46848.0]], shape=(760, 4), dtype=object)

In [49]:
# get our transformed data array back into DataFrames

car_sales_filled_train=pd.DataFrame(filled_X_train,columns=["Make","Colour","Doors","Odometer (KM)"])


car_sales_filled_test=pd.DataFrame(filled_X_test,columns=["Make","Colour","Doors","Odometer (KM)"])

# Check missing data in the train data

car_sales_filled_train.isna().sum()
                                    

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [50]:
# lets one code all the data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                                remainder="passthrough")

transformed_X_train=transformer.fit_transform(car_sales_filled_train)
transformed_X_test=transformer.fit_transform(car_sales_filled_test)

In [51]:
# Check transformed and fill transformed_X_train
transformed_X_train.toarray()

array([[0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.41962e+05],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.40536e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.93629e+05],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.10362e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.05592e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 4.68480e+04]], shape=(760, 15))

In [52]:
# Now we have transformed X lets see we can fit our model or not
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

model=RandomForestRegressor()
model.fit(transformed_X_train,y_train)
model.score(transformed_X_test,y_test)

0.25836662468288074

In [53]:
# Check the length of transformed X data and the len of orginal data
(len(transformed_X_train.toarray())+len(transformed_X_test.toarray())), len(car_sales_missing)
                                                                            

(950, 950)

## Choosing the right estimator/algorithm for our problem

* Sklearn refers to ML models,algorithms as estimators.
* Classification problem- Predecting the category(heart-disease or not)
   * Sometimes you will see clf(short for classifier) used as classification estimator
* Regression problem- Predcting the number (selling price of car)

## Picking machine learning model for regression problem
LET US USE California housing data set

In [54]:
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 

In [55]:
import pandas as pd
housing_df=pd.DataFrame(housing["data"],columns=housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [56]:
housing_df["target"]=housing["target"]
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [57]:
# lets check if any missing data is there or not
housing_df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
target        0
dtype: int64

In [58]:
# lets check wheather all tha data is in numeric form
housing_df.dtypes

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
target        float64
dtype: object

In [61]:
# Import algorith/estimator
from sklearn.linear_model import Ridge
# set up random seed
np.random.seed(42)

# Create X and y
X=housing_df.drop(["target"],axis=1)
y=housing_df["target"]

# import train_test_split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# create a model
model=Ridge()

# fit the model
model.fit(X_train,y_train)

# check the score of model
model.score(X_train,y_train)

0.6125511245209703

In [62]:
# lets check the score on our test data
model.score(X_test,y_test)

0.5758549611440126

# what if Ridge do not match our expectation
 Lets try some other algorithm like ensemble model which is combination of smaller model it is best to try and predict best output

In [64]:
# importing another model for same dta
from sklearn.ensemble import RandomForestRegressor

# set the random_seed
np.random.seed(42)

# Create X and y
X=housing_df.drop(["target"],axis=1)
y=housing_df["target"]

#import train_test_Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# set the model
model=RandomForestRegressor()

# fit the model
model.fit(X_train,y_train)

# lets check the score on training data
model.score(X_train,y_train)


0.9736861165621588

In [65]:
# lets check on the test data
model.score(X_test,y_test)

0.806652667101436

## Now lets see if we are trying the Classification problem which one algorithm we must chose
 lets check which model will provide us the best output

In [66]:
heart_disease=pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [67]:
#Now lets check is our data missing and at the same time we will chwck that all opur data is numeric
heart_disease.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [68]:
heart_disease.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [70]:
# lets import one of the classification model
from sklearn.svm import LinearSVC

# lets set up random seed
np.random.seed(42)

# lets create X, y
X=heart_disease.drop(["target"],axis=1)
y=heart_disease["target"]

#lest import train_test_Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# create a model
model=LinearSVC()

#lets fit the model
model.fit(X_train,y_train)

# lets score 
model.score(X_train,y_train)

0.8553719008264463

In [71]:
# lets check on the test data
model.score(X_test,y_test)

0.8688524590163934

## Lets see using ensemble model will we get better prediction
 As ensemble model are used to get the best predicyion
 

In [72]:
# lets import our model
from sklearn.ensemble import RandomForestClassifier

# set the random seed
np.random.seed(42)

# create train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# create a model
model=RandomForestClassifier()

# fit the model
model.fit(X_train,y_train)
# lest score a model on training data
model.score(X_train,y_train)

1.0

In [74]:
# lets see it on test data 
model.score(X_test,y_test)

0.8524590163934426

## Note :
 1) if you have structure data use ensemble model
 2) if you have unstructure data use transfer learning or deep learning

## Fit the model/algorithim on our data and use it to make prediction
1) fitting the model to the data:
 X: features,features variable ,data
 y: target,labels,target variables

In [75]:
# import a randomforest classifier
from sklearn.ensemble import RandomForestClassifier

# set the random seed
np.random.seed(42)

# import train_test_split
from sklearn.model_selection import train_test_split

# create X,y
X=heart_disease.drop(["target"],axis=1)
y=heart_disease["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# create a model
clf=RandomForestClassifier()

#fit the model
clf.fit(X_train,y_train)

#score the model
clf.score(X_train,y_train)

1.0

In [76]:
# lets score on the testing data
clf.score(X_test,y_test)

0.8524590163934426

In [77]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [78]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

## Make Prediction using a machine learning model
* there are two options
1)predict()
2) predict_proba() 

In [79]:
# USe a trained model to make predictions
clf.predict(np.array([1,7,8,3,4]))

C:\Users\Saurabh Guru\OneDrive\Desktop\sample_project\env\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [82]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [83]:
y_test.tail()

249    0
104    1
300    0
193    0
184    0
Name: target, dtype: int64

In [84]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [85]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])