## Fundamental of Tensorflow:

This Module will help us to prepare a data for Our Deep_Learning Models


# What we are going to cover in this
1) INtroduction to tensors

2) Getting information from tensor

3) Manipulating the tensor

4) Tensor and numpy

5) USing tf.functions

6) Using GPU with tensorflow(or TPU)


In [ ]:

import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
# Lets Create a Scaler tensor
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the dimension of a tensor
scalar.ndim


0

In [ ]:
# Create a vector Tensor
vector=tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# Check the  dimension
vector.ndim

1

In [ ]:
# Lets create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Lets check the dimension
matrix.ndim

2

In [ ]:
# Lets try to create a tensor who has n dimension
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Lets check the dimension of the tensor
tensor.ndim

3

In [ ]:
#Lets create a tensor with tf.variable
changable_tensor=tf.Variable([10,7])
unchangable_tesnor=tf.constant([10,7])

# Now lets try to change the assign value usingf .assign() function
# unchangable_tesnor[0].assign(7)
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Creating a random tensor
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Shuffle the Order of elements in a tensor
not_shuffled=tf.constant([[10,7],
                         [3,8],
                         [9,2]])

tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  8],
       [ 9,  2],
       [10,  7]], dtype=int32)>

In [ ]:
# Creating tensorfrom numpy

# Create a tensor of one
A=tf.ones([10,7])
A

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensors of Zeros
b=tf.zeros(shape=(10,7))
b

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Lets change numpy array into tensors

import numpy as np
C=np.arange(1,25,dtype=np.int32)
D=tf.constant(C)
D

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
E=tf.constant(C,shape=(2,3,4))
E

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
F=tf.constant(C,shape=(6,4))
F

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>


# getting information from tensors
1  SHape

2 Axis or dimension

3  Rank

4  Size


In [ ]:
# Create a tensor of zeros
zeros=tf.zeros(shape=(2,3,4,5))
zeros

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
zeros.shape

TensorShape([2, 3, 4, 5])

In [ ]:
zeros.ndim

4

In [ ]:
zeros.size

AttributeError: EagerTensor object has no attribute 'size'. 
        If you are looking for numpy-related methods, please run the following:
        tf.experimental.numpy.experimental_enable_numpy_behavior()
      

In [ ]:
#v Inedexing Tensors
zeros[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
zeros[:,:2]

<tf.Tensor: shape=(2, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Add an extra dimension to our data
B=zeros[:,:,:,:,tf.newaxis]
B

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

In [ ]:
# alternativ to tf.newaxis
tf.expand_dims(zeros,axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

In [ ]:
tf.expand_dims(zeros,axis=0)

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [ ]:
# lets try to manipualte the tensor using some basic operations
tensor=tf.constant([20,7])
tensor+10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 17], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, -3], dtype=int32)>

In [ ]:
tensor*10


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200,  70], dtype=int32)>

In [ ]:
# we can use tesnorflow built in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200,  70], dtype=int32)>

In [ ]:
# Lets go for matrix multiplication
# we have to use tf.matmul with python we can use @
# Create X and y
X=np.arange(1,10,dtype=np.int32)
y=np.arange(1,25,dtype=np.int32)
A=tf.constant(X,shape=(3,3))
B=tf.constant(y,shape=(3,8))
A,B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [ ]:
tf.matmul(A,B)

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 70,  76,  82,  88,  94, 100, 106, 112],
       [151, 166, 181, 196, 211, 226, 241, 256],
       [232, 256, 280, 304, 328, 352, 376, 400]], dtype=int32)>

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
B=tf.constant([1.7,2.7])
B.dtype

tf.float32

In [ ]:
B=tf.cast(B,dtype=tf.float16)
B.dtype

tf.float16

In [ ]:
# agregating Tensors
D=tf.constant([-1.7,-10.2])
D=abs(D)
D

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.7, 10.2], dtype=float32)>

In [ ]:
E= tf.constant(np.random.randint(1,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([93, 70, 78, 77,  6, 12, 69, 45, 57, 29, 28, 20, 40,  7, 84, 49, 39,
       18,  2, 21, 36, 27, 93, 90, 32,  5, 39, 76, 22, 35, 45, 27, 39, 88,
       99, 85, 29, 52, 42, 77, 58, 75, 57, 37, 71, 73, 49, 59, 51, 96])>

In [ ]:
# Lets find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# lets find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# lets create a mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
# lets get the sum opf the tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2508>

In [ ]:
# Find the  ariance of the tensor
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=723>

In [ ]:
# Find the std of tensor
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.901569366455078>

In [ ]:
# Find the positional maximum and minimum
# Set up a random seed
np.random.seed(42)
A=tf.random.uniform(shape=[100])
A

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.06826472, 0.8906021 , 0.7009065 , 0.4306891 , 0.8419391 ,
       0.23641086, 0.42297685, 0.0395757 , 0.9655719 , 0.8340069 ,
       0.25248218, 0.968246  , 0.9185451 , 0.21427858, 0.6164446 ,
       0.52292395, 0.1733619 , 0.40075457, 0.6846441 , 0.1907295 ,
       0.15954792, 0.35243917, 0.5611944 , 0.22650778, 0.33121634,
       0.51238275, 0.01776671, 0.52935755, 0.6294397 , 0.7693889 ,
       0.68801486, 0.6641973 , 0.8455074 , 0.50363517, 0.0718137 ,
       0.71875453, 0.70814586, 0.40865743, 0.74161816, 0.7304964 ,
       0.86761487, 0.9137176 , 0.50277054, 0.8077823 , 0.32310605,
       0.14442348, 0.2619611 , 0.69101965, 0.4422902 , 0.6105249 ,
       0.5800009 , 0.09883726, 0.13782787, 0.12346518, 0.95187986,
       0.5295242 , 0.11982048, 0.6938896 , 0.00141978, 0.79668283,
       0.51661   , 0.21255243, 0.03486776, 0.701362  , 0.366323  ,
       0.7377428 , 0.6419549 , 0.622167  , 0.76300764, 0.8685374 ,
       0.75645

In [ ]:
# find the positional maximum
tf.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=58>

In [ ]:
A[tf.argmin(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0014197826385498047>

In [ ]:
# find the positional maximum of the tensor
tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=83>

In [ ]:
A[tf.argmax(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9996600151062012>

In [ ]:
# Squeezing a tensor
G=tf.constant(tf.random.uniform(shape=[50]),shape=(10,1,1,1,5))
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.74958634, 0.26587176, 0.6950959 , 0.823086  , 0.49750865],
       [0.6150141 , 0.6097611 , 0.93617964, 0.38570082, 0.9971311 ],
       [0.27476633, 0.6631218 , 0.06593478, 0.33011758, 0.9488106 ],
       [0.48024452, 0.2951988 , 0.53607666, 0.54563534, 0.11033142],
       [0.63493955, 0.7414104 , 0.6735625 , 0.6767272 , 0.76424015],
       [0.13779163, 0.5712316 , 0.47916353, 0.7802321 , 0.7403488 ],
       [0.12756455, 0.8304901 , 0.26091564, 0.49645436, 0.659631  ],
       [0.45915067, 0.7418859 , 0.6842214 , 0.5065485 , 0.93568754],
       [0.0279572 , 0.4689535 , 0.87988746, 0.3971094 , 0.40133882],
       [0.40040183, 0.63186336, 0.945565  , 0.28178012, 0.30915737]],
      dtype=float32)>

In [ ]:
# One_Hot_Encoding
list_1=[0,1,2,3,4]
tf.one_hot(list_1,depth=5,on_value="yess",off_value="no")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'yess', b'no', b'no', b'no', b'no'],
       [b'no', b'yess', b'no', b'no', b'no'],
       [b'no', b'no', b'yess', b'no', b'no'],
       [b'no', b'no', b'no', b'yess', b'no'],
       [b'no', b'no', b'no', b'no', b'yess']], dtype=object)>

In [ ]:
# Making some other operations
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
! nvidia-smi

Sat Sep 27 12:52:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
s